work around ResultLog support for pytest>=6.1
pytest-dev/pytest-rerunfailures pull request #129
Opened 2020-09-26 23:56 UTC by ntessore

This is a workaround that closes #128. It does not address potential integration with the reportlog plugin.

2020-09-27 01:17 UTC, gnikonorov approved these changes
As an immediate fix to stop the fatal error, I think this is OK. I will defer to @sallner and/or @icemac for the merge.

@ntessore if this gets merged can you open a separate issue to track integration with `reportlog` so it doesn't get lost?

2020-09-27 01:21 UTC, gnikonorov commented
Could you also add a changelog entry to this PR, @ntessore? It can be added in the  [CHANGES.rst](https://github.com/pytest-dev/pytest-rerunfailures/blob/master/CHANGES.rst) file

2020-09-27 10:03 UTC, ntessore commented
@gnikonorov I'm really not qualified to open an issue on pytest plugin interoperability, I wouldn't even know if that should be an issue here or in pytest-dev/pytest-reportlog.

2020-09-28 00:21 UTC, gnikonorov requested changes
Just a small nitpickish comment on the changelog text

2020-09-28 00:21 UTC, gnikonorov commented on CHANGES.rst
> +- Deprecated `--result-log` was removed in pytest 6.1.0.
Nit: can we change the wording a bit to something like 'Deprecate `--result-log`, as it was removed in  pytest 6.1.0 )'

2020-09-28 00:22 UTC, gnikonorov commented
> @gnikonorov I'm really not qualified to open an issue on pytest plugin interoperability, I wouldn't even know if that should be an issue here or in pytest-dev/pytest-reportlog.

@ntessore I'll open one then. Thank you for fixing the crash

2020-09-28 06:31 UTC, icemac commented on CHANGES.rst
> +- Deprecated `--result-log` was removed in pytest 6.1.0.
```suggestion
- Deprecate ``--result-log``, as it was removed in pytest 6.1.0
```

2020-09-28 13:47 UTC, nicoddemus approved these changes

2020-09-28 14:02 UTC, sallner commented
I am unhappy with the fact, that we have now 3 ways of handling the resultlog in this plugin, but it seems that a bugfix release might be appropriate to make various CIs green again.

2020-09-28 14:04 UTC, sallner approved these changes
I will merge the changes and cut a release as 9.1.1. We can clean up the rest afterwards.

2020-09-28 14:06 UTC, merged

2020-09-29 06:14 UTC, icemac commented
> I will merge the changes and cut a release as 9.1.1. We can clean up the rest afterwards.

Maybe it should become a 9.2 or even 10.0 as the `--result-log` command line option is no linger supported when this plug-in is used together with pytest >= 6.1.

2020-09-29 06:32 UTC, sallner commented
@ntessore Thanks for the work, version 9.1.1 is out with the workaround. https://pypi.org/project/pytest-rerunfailures/9.1.1/ Let's see, what we will do with the clean up, and if we need to support resultlog in the future.

2020-09-29 07:14 UTC, hugovk commented
Thank you all for the quick fix and release!