Test with current pytest versions.
pytest-dev/pytest-rerunfailures pull request #138
Opened 2020-09-28 14:57 UTC by sallner

This is an exception to rule of the last 5 minor versions of pytest, as this is just the bug fix and a quick workaround. The other versions will be dropped in next minor version.

2020-09-28 15:27 UTC, hugovk approved these changes

2020-09-28 15:37 UTC, gnikonorov reviewed
@sallner was the removal of v5.4.1 from `.travis.yml` intentional?

2020-09-28 15:45 UTC, hugovk commented
I think so: 5.4.1 has been replaced with the newest 5.4, that is, 5.4.3.

2020-09-28 15:49 UTC, gnikonorov approved these changes
You're right @hugovk, I misread sorry.

LGTM

2020-09-28 19:26 UTC, sallner commented
It really takes ages with such a big test matrix.

2020-09-29 05:58 UTC, icemac requested changes
I thought the current policy is to support only the latest 5 pytest feature releases. So adding 6.0 and 6.1 our require to drop 5.0 and 5.1. This also reduces the test matrix by 10 test jobs.

2020-09-29 05:59 UTC, icemac approved these changes

2020-09-29 06:07 UTC, merged